// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Employment.Migrations
{
    [DbContext(typeof(context))]
    [Migration("20240828084531_first")]
    partial class first
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Users", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AfradTafakol")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Bime")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BirthDay")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ChildNum")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CodeMeli")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreateDateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Din")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FatherFullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FatherJob")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FatherName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FatherStudy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("GovahiRanandegi")
                        .HasColumnType("bit");

                    b.Property<string>("LangConv")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MahaleSodor")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Meliat")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MoterJob")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MotherFullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MotherStudy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Points")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Sarbazi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("canDorKari")
                        .HasColumnType("bit");

                    b.Property<bool>("canZemanat")
                        .HasColumnType("bit");

                    b.Property<string>("corse1Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("corse1Time")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("corse2Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("corse2Time")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("englishConv")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("englishUndrestand")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("englishWrite")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("exjob2Company")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("exjob2End")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("exjob2Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("exjob2Pay")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("exjob2Phone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("exjob2Reason")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("exjob2Start")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("exjobCompany")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("exjobEnd")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("exjobName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("exjobPay")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("exjobPhone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("exjobReason")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("exjobStart")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("friendFullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("friendJob")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("friendPhone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("friendRel")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("haveSopishine")
                        .HasColumnType("bit");

                    b.Property<string>("howFind")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("isFullTime")
                        .HasColumnType("bit");

                    b.Property<bool>("isSingle")
                        .HasColumnType("bit");

                    b.Property<bool>("isStuding")
                        .HasColumnType("bit");

                    b.Property<bool>("isTobacco")
                        .HasColumnType("bit");

                    b.Property<bool>("isWorking")
                        .HasColumnType("bit");

                    b.Property<string>("langName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("langUnderstand")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("langWrite")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("payment")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("phoneSabet")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("phoneSos")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("rel1Fullname")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("rel1Job")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("rel1Rel")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("rel1Study")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("rel2Fullname")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("rel2Job")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("rel2Rel")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("rel2Study")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("rezomePath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("soft1Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("soft1lvl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("soft2Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("soft2lvl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("soft3Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("soft3lvl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("startDate")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("study2Finish")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("study2History")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("study2Scholl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("study2Score")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("study2lvl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("studyFinish")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("studyHistory")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("studyScholl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("studyScore")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("studylvl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("wishedJob")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users_tbl");
                });
#pragma warning restore 612, 618
        }
    }
}
